version: '2'

services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: sh
    command: -c 'mkdir -p /data/notea && /usr/bin/minio server /data'
